INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (1, 'Antiques', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (2, 'Art', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (3, 'Automotive', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (4, 'Baby', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (5, 'Books', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (6, 'Business & Industrial', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (7, 'Cameras & Photo', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (8, 'Clothing & Accessories', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (9, 'Collectibles', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (10, 'Computers', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (11, 'Crafts', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (12, 'DVD\'s & Movies', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (13, 'Electronics', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (14, 'Health & Beauty', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (15, 'Home & Garden', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (16, 'Jewelry & Watches', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (17, 'Music', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (18, 'Pet Supplies', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (19, 'Services', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (20, 'Sports & Outdoors', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (21, 'Sports Memorabilia & Cards', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (22, 'Tools & Home Imporvement', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (23, 'Toys & Hobbies', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (24, 'Video Games', 0, 1);
INSERT INTO `trade_categories` (`catID`, `name`, `parentID`, `status`) VALUES (25, 'Other', 0, 1);